const fs = require('fs');
const path = require('path');

const imagesDir = path.join(__dirname, '..', 'src', 'images');
const outFile = path.join(__dirname, '..', 'src', 'components', 'gallery.html');

function isImage(name) {
  return /\.(jpg|jpeg|png|gif|webp|svg)$/i.test(name);
}

function encodeForUrl(p) {
  return p.split(path.sep).map(encodeURIComponent).join('/');
}

function build() {
  if (!fs.existsSync(imagesDir)) {
    console.error('images dir not found:', imagesDir);
    process.exit(1);
  }

  const folders = fs.readdirSync(imagesDir, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);

  // build filters (folder names) and items
  let filtersHtml = folders.map(f => `  <button class="filter">${f}</button>`).join('\n');

  // collect image tags
  const items = [];
  let idx = 0;
  for (const folder of folders) {
    const folderPath = path.join(imagesDir, folder);
    const files = fs.readdirSync(folderPath).filter(isImage);
    for (const file of files) {
      const rel = `images/${encodeForUrl(folder)}/${encodeURIComponent(file)}`;
      // pick a span based on position for visual variety
      let spanClass = 'item--span-1x1';
      if (idx % 11 === 0) spanClass = 'item--span-3x3';
      else if (idx % 7 === 0) spanClass = 'item--span-2x2';
      else if (idx % 5 === 0) spanClass = 'item--span-1x2';
      items.push(`  <div class="item ${spanClass}"><img src="${rel}" alt="${folder} - ${file}"/></div>`);
      idx++;
    }
  }

  const html = `<!-- Generated by scripts/generate-gallery.js -->\n<div class="filters">\n  <button class="filter active">All</button>\n${filtersHtml}\n</div>\n\n<section class="grid">\n${items.join('\n')}\n</section>\n`;

  fs.writeFileSync(outFile, html, 'utf8');
  console.log('Wrote', outFile);
}

build();
